/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author diego
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Workbench = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        CalcNom = new javax.swing.JMenuItem();
        ImpNom = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SalSys = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        ToolDep = new javax.swing.JMenuItem();
        ToolPuesto = new javax.swing.JMenuItem();
        ToolConcepto = new javax.swing.JMenuItem();
        ToolEmpleado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout WorkbenchLayout = new javax.swing.GroupLayout(Workbench);
        Workbench.setLayout(WorkbenchLayout);
        WorkbenchLayout.setHorizontalGroup(
            WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        WorkbenchLayout.setVerticalGroup(
            WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        File.setText("Archivo");

        CalcNom.setText("Calcular Nómina");
        CalcNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcNomActionPerformed(evt);
            }
        });
        File.add(CalcNom);

        ImpNom.setText("Imprimir Nómina");
        ImpNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpNomActionPerformed(evt);
            }
        });
        File.add(ImpNom);
        File.add(jSeparator1);

        SalSys.setText("Salir del Sistema");
        File.add(SalSys);

        jMenuBar1.add(File);

        Tools.setText("Mantenimiento");

        ToolDep.setText("Departamentos");
        ToolDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolDepActionPerformed(evt);
            }
        });
        Tools.add(ToolDep);

        ToolPuesto.setText("Puestos");
        ToolPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolPuestoActionPerformed(evt);
            }
        });
        Tools.add(ToolPuesto);

        ToolConcepto.setText("Conceptos");
        ToolConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolConceptoActionPerformed(evt);
            }
        });
        Tools.add(ToolConcepto);

        ToolEmpleado.setText("Empleados");
        ToolEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolEmpleadoActionPerformed(evt);
            }
        });
        Tools.add(ToolEmpleado);

        jMenuBar1.add(Tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workbench)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workbench)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImpNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImpNomActionPerformed

    private void ToolDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolDepActionPerformed
        FrmMantDep fDM = new FrmMantDep();
        Workbench.add(fDM);
        fDM.setVisible(true);
    }//GEN-LAST:event_ToolDepActionPerformed

    private void ToolPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolPuestoActionPerformed
        FrmMantPuesto fDM = new FrmMantPuesto();
        Workbench.add(fDM);
        fDM.setVisible(true);
    }//GEN-LAST:event_ToolPuestoActionPerformed

    private void ToolConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolConceptoActionPerformed
        FrmMantConcepto fDM = new FrmMantConcepto();
        Workbench.add(fDM);
        fDM.setVisible(true);
    }//GEN-LAST:event_ToolConceptoActionPerformed

    private void ToolEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolEmpleadoActionPerformed
        FrmMantEmp fDM = new FrmMantEmp();
        Workbench.add(fDM);
        fDM.setVisible(true);
    }//GEN-LAST:event_ToolEmpleadoActionPerformed

    private void CalcNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CalcNom;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem ImpNom;
    private javax.swing.JMenuItem SalSys;
    private javax.swing.JMenuItem ToolConcepto;
    private javax.swing.JMenuItem ToolDep;
    private javax.swing.JMenuItem ToolEmpleado;
    private javax.swing.JMenuItem ToolPuesto;
    private javax.swing.JMenu Tools;
    private javax.swing.JDesktopPane Workbench;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
